config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages
  post '/messages/:id', to: 'messages#update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  enum result: { result_ok: 1, result_wait: 2, result_ng: 3, report_to_management: 4 }

  def call
    sid = Rails.application.credentials.dig(:twilio, :sid)
    token = Rails.application.credentials.dig(:twilio, :token)
    from_number = Rails.application.credentials.dig(:twilio, :phone_number)

    client = Twilio::REST::Client.new sid, token
    msg = Twilio::TwiML::VoiceResponse.new do |r|
      r.say voice: 'Alice', language: 'ja-JP', message: '自動告白サービス。告白の行方です。'
      r.pause length: 1
      r.say voice: 'Alice', language: 'ja-JP', message: "#{to_name}様。#{from_name}様よりメッセージがございます。"
      r.pause length: 2
      r.say voice: 'Polly.Takumi', language: 'ja-JP', message: message
      r.say voice: 'Polly.Takumi',  language: 'ja-JP', message: message
      r.pause length: 1
      r.gather action: Rails.application.routes.url_helpers.message_url(id), method: 'POST', numDigits: 1 do |g|
        g.say voice: 'Alice', language: 'ja-JP', message: 'この告白にOKの場合は1を。。。もう一度考える場合は2を。。。ごめんなさいの場合は3を入力してください。'
        r.pause length: 2
        g.say voice: 'Alice', language: 'ja-JP', message: '運営に通報する場合は4を入力してください'
      end
    end

    phone = "+81" + phone_number.gsub('-', '').gsub(/\A0/, '')
    client.calls.create(
      twiml: msg.to_s,
      to: phone,
      from: from_number
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session, only: %i[update]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        @message.call
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    result = params[:Digits].to_i
    @message.update!(result: result)
    msg = Twilio::TwiML::VoiceResponse.new do |r|
      r.say voice: 'Alice', language: 'ja-JP', message: 'ご利用ありがとうございました'
    end
    render xml: msg
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:phone_number, :from_name, :to_name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwilioSample2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.slim
.card
  .card-header
    h4.card-title 告白一覧
    .card-tools
      = link_to '新規登録', new_message_path, class: 'btn btn-outline-primary'
  .card-body
    table.table.table-bordered
      thead
        tr
          th = Message.human_attribute_name :from_name
          th = Message.human_attribute_name :to_name
          th = Message.human_attribute_name :result
          th
      tbody
        - @messages.each do |message|
          tr
            td = message.from_name
            td = message.to_name
            td = message.result_i18n
            td = link_to '詳細', message_path(message), class: 'btn btn-outline-secondary'

app/views/messages/new.html.slim
.card
  .card-header
    h4.card-title 告白登録
  .card-body
    = bootstrap_form_with model: @message do |f|
      = f.text_field :from_name
      = f.text_field :to_name
      = f.password_field :phone_number
      = f.text_area :message
      .btn-submit.text-center
        = f.submit '告白する', class: 'btn btn-primary'

app/views/messages/show.html.slim
.card
  .card-header
    h4.card-title 告白詳細
    .card-tools
      = link_to '戻る', messages_path, class: 'btn btn-outline-secondary'
  .card-body
    table.table.table-striped
      tr
        th = Message.human_attribute_name(:result)
        td = @message.result_i18n
      tr
        th = Message.human_attribute_name(:from_name)
        td = @message.from_name
      tr
        th = Message.human_attribute_name(:to_name)
        td = @message.to_name
      tr
        th = Message.human_attribute_name(:phone_number)
        td xxxxxxxxxxxxxxx
      tr
        th = Message.human_attribute_name(:message)
        td = @message.message